# Generated by Django 5.0.2 on 2026-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delivery_zone',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('rider', 'Rider')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_details',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
